#! /bin/bash

removedriver()
{
	rmmod NEWCDD
	dmesg | less -10
	read
	lsmod | head -5
	read
	cat /proc/devices
	read
	make clean
	unlink myNODE
	rm -f user_app
}

app()
{
	echo
        read -p "Compile Application (y/n) " resp
        if [ $resp == 'y' ]
        then
		echo
		if ( make user_app)
		then
			echo
			read -n1 -p "Compilation Successfull. Run app ?? (y/n) " resp
			if [ $resp == 'y' ]
			then
				./user_app
			else
				echo "Good luck"
			fi
		else
			echo
			echo "Compilation failed"
		fi
	fi
}

insertdriver()
{
	insmod NEWCDD.ko
	dmesg | less -6
	echo
	read -p "Enter MajorNo." resp
	major=$resp
	mknod ./dev/myNODE c $major 0
	lsmod | head -5
	read
	cat /proc/devices
	read
	
	app ## Calling our application to compile and run ##

	echo
	read -p "Do u want to remove driver (y/n)" resp
	if [ $resp == 'y' ]
	then
		removedriver
		echo "Driver removed & cleaned !! Good Byee!"
		echo
	else
		echo "Driver didn't removed!"
		echo
	fi


}
builddriver()
{
	if ( make )
	then 
		echo
		read -p "Compilation Successfull. Do you want to insert Driver (y/n)" resp
		if [ $resp == 'y' ]
		then
			insertdriver	
		else
			echo "Driver cleaned !! Good Byee!"
			make clean
			echo
		fi
	else
		echo "Compilation Failed."
	fi
}

#Starting point of the script
builddriver

######################################################################################################
